In [8]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

**Training Image Preprocessing**

In [9]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 70295 files belonging to 38 classes.


**Validation Image Preprocessing**

In [10]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 17572 files belonging to 38 classes.


In [12]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[154.75 144.75 152.75]
   [138.25 128.25 136.25]
   [151.25 141.25 149.25]
   ...
   [200.5  195.5  201.5 ]
   [204.5  199.5  205.5 ]
   [203.   198.   204.  ]]

  [[155.   145.   153.  ]
   [144.5  134.5  142.5 ]
   [137.75 127.75 135.75]
   ...
   [201.25 196.25 202.25]
   [200.75 195.75 201.75]
   [196.   191.   197.  ]]

  [[145.25 135.25 143.25]
   [154.75 144.75 152.75]
   [139.5  129.5  137.5 ]
   ...
   [201.5  196.5  202.5 ]
   [196.   191.   197.  ]
   [194.25 189.25 195.25]]

  ...

  [[133.5  121.5  131.5 ]
   [145.   133.   143.  ]
   [148.5  136.5  146.5 ]
   ...
   [165.75 159.75 173.75]
   [172.75 166.75 180.75]
   [156.25 150.25 164.25]]

  [[127.75 115.75 125.75]
   [138.25 126.25 136.25]
   [144.   132.   142.  ]
   ...
   [195.75 189.75 203.75]
   [189.75 183.75 197.75]
   [191.5  185.5  199.5 ]]

  [[137.   125.   135.  ]
   [137.25 125.25 135.25]
   [138.25 126.25 136.25]
   ...
   [161.25 155.25 169.25]
   [151.   145.   159.  ]
   [164.5  158.5  17

In [ ]:
import numpy as np
import pandas as pd